---
# Ansible playbook for a Docker for Mac Replacement.
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update all system packages
      package:
        name: "*"
        state: latest

  roles:
    - geerlingguy.ntp
    - geerlingguy.docker
    - docker.grub
    - docker.dns
    - docker.selinux
    - docker.config

  post_tasks:
    - name: IMPORTANT NOTICE
      debug:
        msg: 'To finish provisioning please run "vagrant reload"'
