---
- name: configure docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "dns": [
          "{{ ansible_ssh_host }}"
        ],
        {% if ansible_facts.selinux.status == 'enabled' %}
        "selinux-enabled": true,
        {% endif %}
      }
  notify:
    - restart docker service
